### ISSUE TITLE
blacklist -> translate -> map incorrectly matches a source artifact

### ISSUE THREAD

**Issue by michel-slm** [nebula-plugins/gradle-blacklist-plugin#1]
With gradle-blacklist-plugin 1.12.0 and 2.2.0, 

```
blacklist {
  translate {
   map 'org.bouncycastle:bcprov-jdk16', "org.bouncycastle:bcprov-jdk15on:$bouncyCastleVersion"
  }
}
```

not only maps

```
org.bouncycastle:bcprov-jdk16:1.46 -> org.bouncycastle:bcprov-jdk15on:1.52
```

but also

```
org.bouncycastle:bctsp-jdk14:1.38 -> org.bouncycastle:bcprov-jdk15on:1.52
org.bouncycastle:bcpkix-jdk15on:1.52 -> org.bouncycastle:bcprov-jdk15on:1.52
```

Seems like only the group ID is matched?

**Comment by michel-slm** [comment]
ps gradle-blacklist-plugin 3 does not seem to be available in either maven central or jcenter, which is why I tried 2.2.0

**Comment by sghill** [comment]
Closing this with the merge of PR #3 and release of v3.1.0.

Please check out [nebula-plugins/gradle-resolution-rules-plugin](https://github.com/nebula-plugins/gradle-resolution-rules-plugin), which is actively supported and also provides solutions in this problem space.
